id: I66E85586
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:13.608662
last_modified: 2023-01-04 11:29:13.608676
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  95AC:
    title: Light from the Wisdom Sun
    base_file: 95AC.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
